[package]
name = "chronokey-token-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chronokey-core = { path = "../chronokey-core" }
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
